language: python

addons:
  apt:
    packages:
      - mecab
      - libmecab-dev
      - mecab-ipadic-utf8

before_install:
  - wget http://www.phontron.com/kytea/download/kytea-0.4.7.tar.gz
  - tar zxvf kytea-0.4.7.tar.gz
  - cd kytea-0.4.7 && ./configure && sudo make && sudo make install && cd ..
  - sudo ldconfig -v

install:
  - pip install -r requirements.txt
  - pip install .

python:
      - 3.6

script:
      - nosetests tests
